### ISSUE TITLE
Provide the built DLL

### ISSUE THREAD

**Issue by kamranayub** [ShabbyX/libpandoc#2]
If the built DLL is platform-independent, it would be nice to provide a way to download it so we don't have to go through the pains of compiling everything.

I can't figure out how to build this... have no Haskell experience at all. I just want the .NET DLL! :)

**Comment by ShabbyX** [comment]
If you want the .Net DLL, you should probably refer to https://github.com/t0yv0/libpandoc-dotnet

However, `libpandoc` has just been transferred to me, and the original author (t0yv0) would not be maintaining that repository as far as I can tell. I am afraid you would need to figure it out yourself. I am closing this issue since it's very old.
